apiVersion: v1
kind: Service
metadata:
  name: knx-curator-processing-service
  namespace: bd
spec:
  ports:
    - port: 3006
      targetPort: 3006
      protocol: TCP
  type: NodePort
  selector:
    app: knx-curator-processing
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: knx-curator-processing
  namespace: bd
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: knx-curator-processing
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: knx-curator-processing
  name: knx-curator-processing
  namespace: bd
spec:
  selector:
    matchLabels:
      app: knx-curator-processing
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: knx-curator-processing
    spec:
      containers:
      - image: 940643983093.dkr.ecr.ap-southeast-1.amazonaws.com/knx-curator-processing-staging:1
        name: knx-curator-processing
        env:
        - name: NODE_ENV
          value: staging
        - name: MONGO_URI
          value: 10.0.203.196
        ports:
        - containerPort: 3006
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 3006
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "400m"
            memory: "256Mi"
      restartPolicy: Always