apiVersion: v1
kind: Service
metadata:
  name: curator-cron-service
  namespace: bd
spec:
  ports:
    - port: 3333
      targetPort: 3333
      protocol: TCP
  type: NodePort
  selector:
    app: curator-cron
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: curator-cron
  namespace: bd
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: curator-cron
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: curator-cron
  name: curator-cron
  namespace: bd
spec:
  selector:
    matchLabels:
      app: curator-cron
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: curator-cron
    spec:
      containers:
      - image: 940643983093.dkr.ecr.ap-southeast-1.amazonaws.com/knx-curator-cron-staging:74
        name: curator-cron
        env:
        - name: NODE_ENV
          value: staging
        - name: MONGO_URI
          value: 10.0.203.196:27017
        ports:
        - containerPort: 3333
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 3333
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "250m"
            memory: "256Mi"
      restartPolicy: Always