apiVersion: v1
kind: Service
metadata:
  name: curator-mediaservice-service
  namespace: bd
spec:
  ports:
    - port: 3939
      targetPort: 3939
      protocol: TCP
  type: NodePort
  selector:
    app: curator-media-service
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: curator-media-service
  namespace: bd
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: curator-media-service
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: curator-media-service
  name: curator-media-service
  namespace: bd
spec:
  selector:
    matchLabels:
      app: curator-media-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: curator-media-service
    spec:
      hostAliases:
      - ip: "10.0.203.196"
        hostnames:
        - "mongo"
      containers:
      - image: 940643983093.dkr.ecr.ap-southeast-1.amazonaws.com/knx-curator-media-service-staging:74
        name: curator-media-service
        env:
        - name: ENV
          value: staging
        ports:
        - containerPort: 3939
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 3939
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "400m"
            memory: "256Mi"
      restartPolicy: Always